/*
 * generated by Xtext
 */
package org.softlang.megal.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MegalUiModule extends org.softlang.megal.language.ui.AbstractMegalUiModule {
	public MegalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
