/*
 * generated by Xtext
 */
package org.softlang.megal.language.ui.contentassist

import org.softlang.megal.language.ui.contentassist.AbstractMegalProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MegalProposalProvider extends AbstractMegalProposalProvider {
}
